# Generated by Django 3.1 on 2020-08-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BioOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('virus', models.CharField(max_length=100)),
                ('protien', models.CharField(max_length=100)),
                ('other', models.CharField(max_length=100)),
                ('smile', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('other_thing1', models.CharField(max_length=100)),
                ('other_thing2', models.CharField(max_length=100)),
            ],
        ),
    ]
